/**
 * Syna Systems — Audit Generation Agent
 *
 * Reads prospect dossier + audit framework → generates personalized audit report.
 * Uses OpenRouter via shared openai_client.
 *
 * SECURITY: No hardcoded API keys. OPENROUTER_API_KEY from env only.
 */

import { generate } from './lib/openai_client.js';
import { loadLeads, Lead } from './lib/csv_loader.js';
import { logAction } from './lib/logger.js';
import { slugify, ensureDir, writeAudit, readFileContent, fileExists } from './lib/file_utils.js';
import path from 'path';

// ─── Constants ──────────────────────────────────────────────
const DOSSIERS_DIR = 'D:/ShivamGem/SynaSystems/agency-brain/dossiers';
const AUDITS_DIR = 'D:/ShivamGem/SynaSystems/agency-brain/audits';

const AUDIT_FRAMEWORK_PATH = 'D:/ShivamGem/SynaSystems/agency-brain/operations/audit_framework.md';
const ICP_FRAMEWORK_PATH = 'D:/ShivamGem/SynaSystems/agency-brain/operations/ICP_FRAMEWORK.md';
const DELIVERY_FRAMEWORK_PATH = 'D:/ShivamGem/SynaSystems/agency-brain/operations/14_day_delivery_framework.md';

const AGENT_ID = 'audit-gen-agent';

// ─── System Prompt ──────────────────────────────────────────
const SYSTEM_PROMPT = `You are a senior operational infrastructure consultant at Syna Systems. Generate a personalized operational audit report for a healthcare organization.

You will receive: the company's prospect dossier, our audit framework template, ICP criteria, and delivery framework.

Generate in this EXACT format:

# Operational Audit Report: {Company Name}
## Prepared by Syna Systems | {Date}
## Classification: Confidential

---

### Executive Summary
3-4 sentences with key findings and estimated annual revenue leakage.

### 1. Human Middleware Assessment
Where this company uses humans as API connectors between systems.

### 2. Scaling Constraint Analysis
Why hiring more staff won't scale their RCM operations.

### 3. Automation ROI Projection
| Metric | Current (Est.) | With Syna PDMS | Improvement |
|---|---|---|---|
| First-Pass Denial Rate | X% | Y% | Z% |
| Appeal Turnaround | X days | Y days | Z% faster |
| Revenue Recovery | $X/month | $Y/month | +$Z/month |
| Staff Hours on Appeals | X hrs/week | Y hrs/week | Z hrs saved |

### 4. Security & Compliance Readiness
HIPAA assessment for AI integration with their EHR.

### 5. Recommended 14-Day Velocity Pilot
Specific department, integration points, success metrics, timeline.

### 6. Risk Assessment
Implementation risks, mitigation, change management.

---
*Generated by Syna Systems Operational Assessment Engine*

Use concrete numbers (estimate based on org size/type). Reference their specific EHR. Make every section specific to THIS prospect — never generic.`;

// ─── Core Export ─────────────────────────────────────────────

export interface AuditFrameworks {
  audit: string;
  icp: string;
  delivery: string;
}

/**
 * Generate a personalized audit report for a single lead.
 *
 * @param lead       - The lead record from CSV
 * @param frameworks - Pre-loaded framework content (audit, icp, delivery)
 * @param dryRun     - If true, skip LLM call and print what would happen
 * @returns The generated audit markdown, or null if dossier not found / skipped
 */
export async function generateAudit(
  lead: Lead,
  frameworks: AuditFrameworks,
  dryRun?: boolean
): Promise<string | null> {
  const slug = slugify(lead.Organization);
  const dossierPath = `${DOSSIERS_DIR}/${slug}.md`;

  // ── Guard: dossier must exist ──
  if (!fileExists(dossierPath)) {
    console.warn(`[SKIP] No dossier found for "${lead.Organization}" at ${dossierPath}`);
    await logAction(AGENT_ID, 'audit_gen', `Skipped ${lead.Organization} — no dossier`, 'SKIPPED', '');
    return null;
  }

  const dossier = readFileContent(dossierPath);

  if (dryRun) {
    console.log(`[DRY-RUN] Would generate audit for "${lead.Organization}"`);
    console.log(`  Dossier: ${dossierPath} (${dossier.length} chars)`);
    console.log(`  Frameworks loaded: audit(${frameworks.audit.length}), icp(${frameworks.icp.length}), delivery(${frameworks.delivery.length})`);
    return null;
  }

  // ── Build user prompt ──
  const today = new Date().toISOString().split('T')[0];
  const userPrompt = `
=== PROSPECT DOSSIER ===
${dossier}

=== AUDIT FRAMEWORK ===
${frameworks.audit}

=== ICP FRAMEWORK ===
${frameworks.icp}

=== 14-DAY DELIVERY FRAMEWORK ===
${frameworks.delivery}

=== INSTRUCTIONS ===
Company Name: ${lead.Organization}
Primary EHR: ${lead.Primary_EHR || lead.Primary_EHR_Placeholder || 'Unknown'}
Location: ${lead.Location}
Qualification Score: ${lead.Qualification_Score}
Date: ${today}

Generate the full operational audit report now. Use concrete, estimated numbers. Reference their EHR system specifically.
`.trim();

  console.log(`[AUDIT] Generating audit for "${lead.Organization}"...`);

  try {
    const auditContent = await generate(SYSTEM_PROMPT, userPrompt);
    const outputPath = writeAudit(slug, auditContent);

    await logAction(
      AGENT_ID,
      'audit_gen',
      `Generated audit for ${lead.Organization} (${auditContent.length} chars)`,
      'DONE',
      outputPath
    );

    console.log(`  ✓ Audit written: ${outputPath}`);
    return auditContent;
  } catch (err) {
    const errMsg = err instanceof Error ? err.message : String(err);
    console.error(`[ERROR] Audit generation failed for "${lead.Organization}": ${errMsg}`);
    await logAction(AGENT_ID, 'error', `Audit gen failed: ${lead.Organization} — ${errMsg}`, 'ERROR', '');
    return null;
  }
}

// ─── CLI Main ────────────────────────────────────────────────

function parseArgs(): { company?: string; score?: string; dryRun: boolean; limit: number } {
  const args = process.argv.slice(2);
  let company: string | undefined;
  let score: string | undefined;
  let dryRun = false;
  let limit = Infinity;

  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
      case '--company':
        company = args[++i];
        break;
      case '--score':
        score = args[++i];
        break;
      case '--dry-run':
        dryRun = true;
        break;
      case '--limit':
        limit = parseInt(args[++i], 10);
        break;
    }
  }

  return { company, score, dryRun, limit };
}

/**
 * Load all three reference frameworks from disk.
 */
export function loadFrameworks(): AuditFrameworks {
  console.log('[BOOT] Loading reference frameworks...');
  const audit = readFileContent(AUDIT_FRAMEWORK_PATH);
  console.log(`  ✓ Audit framework: ${audit.length} chars`);
  const icp = readFileContent(ICP_FRAMEWORK_PATH);
  console.log(`  ✓ ICP framework: ${icp.length} chars`);
  const delivery = readFileContent(DELIVERY_FRAMEWORK_PATH);
  console.log(`  ✓ Delivery framework: ${delivery.length} chars`);
  return { audit, icp, delivery };
}

// ── isMain pattern: run only when invoked directly ──
const isMain =
  process.argv[1] &&
  (process.argv[1].includes('audit_generator') ||
   process.argv[1].endsWith('audit_generator.ts'));

if (isMain) {
  (async () => {
    console.log('══════════════════════════════════════════');
    console.log('  SYNA SYSTEMS — AUDIT GENERATION AGENT');
    console.log('══════════════════════════════════════════\n');

    const { company, score, dryRun, limit } = parseArgs();

    // Load frameworks
    const frameworks = loadFrameworks();

    // Load leads with filters
    const leads = await loadLeads({ company, score });
    const batch = leads.slice(0, limit);

    console.log(`\n[RUN] Processing ${batch.length} lead(s)${dryRun ? ' (DRY RUN)' : ''}...\n`);

    let generated = 0;
    let skipped = 0;

    for (let i = 0; i < batch.length; i++) {
      const lead = batch[i];
      console.log(`\n▶ [${i + 1}/${batch.length}] ${lead.Organization}`);
      const result = await generateAudit(lead, frameworks, dryRun);
      if (result) {
        generated++;
      } else {
        skipped++;
      }
    }

    console.log('\n══════════════════════════════════════════');
    console.log(`  AUDIT GENERATION COMPLETE`);
    console.log(`  Generated: ${generated} | Skipped: ${skipped}`);
    console.log('══════════════════════════════════════════\n');

    await logAction(
      AGENT_ID,
      'audit_gen',
      `Batch complete: ${generated} generated, ${skipped} skipped out of ${batch.length}`,
      'DONE',
      AUDITS_DIR
    );
  })();
}
